/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsWorkspacesRouteImport } from './routes/docs.workspaces'
import { Route as DocsUninstallRouteImport } from './routes/docs.uninstall'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsSqlHistoryRouteImport } from './routes/docs.sql-history'
import { Route as DocsSharingRouteImport } from './routes/docs.sharing'
import { Route as DocsShareChatRouteImport } from './routes/docs.share-chat'
import { Route as DocsSampleDataRouteImport } from './routes/docs.sample-data'
import { Route as DocsReportBugRouteImport } from './routes/docs.report-bug'
import { Route as DocsQuickStartRouteImport } from './routes/docs.quick-start'
import { Route as DocsQueryingRouteImport } from './routes/docs.querying'
import { Route as DocsPrivacyRouteImport } from './routes/docs.privacy'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsImportingCsvRouteImport } from './routes/docs.importing-csv'
import { Route as DocsHelpRouteImport } from './routes/docs.help'
import { Route as DocsHashingRouteImport } from './routes/docs.hashing'
import { Route as DocsFirstWorkspaceRouteImport } from './routes/docs.first-workspace'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsDataFlowRouteImport } from './routes/docs.data-flow'
import { Route as DocsCollaborateRouteImport } from './routes/docs.collaborate'
import { Route as DocsClaudeSetupRouteImport } from './routes/docs.claude-setup'
import { Route as DocsChatgptSetupRouteImport } from './routes/docs.chatgpt-setup'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWorkspacesRoute = DocsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUninstallRoute = DocsUninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSqlHistoryRoute = DocsSqlHistoryRouteImport.update({
  id: '/sql-history',
  path: '/sql-history',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSharingRoute = DocsSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsShareChatRoute = DocsShareChatRouteImport.update({
  id: '/share-chat',
  path: '/share-chat',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSampleDataRoute = DocsSampleDataRouteImport.update({
  id: '/sample-data',
  path: '/sample-data',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReportBugRoute = DocsReportBugRouteImport.update({
  id: '/report-bug',
  path: '/report-bug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQueryingRoute = DocsQueryingRouteImport.update({
  id: '/querying',
  path: '/querying',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPrivacyRoute = DocsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsImportingCsvRoute = DocsImportingCsvRouteImport.update({
  id: '/importing-csv',
  path: '/importing-csv',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHelpRoute = DocsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHashingRoute = DocsHashingRouteImport.update({
  id: '/hashing',
  path: '/hashing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFirstWorkspaceRoute = DocsFirstWorkspaceRouteImport.update({
  id: '/first-workspace',
  path: '/first-workspace',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDataFlowRoute = DocsDataFlowRouteImport.update({
  id: '/data-flow',
  path: '/data-flow',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCollaborateRoute = DocsCollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClaudeSetupRoute = DocsClaudeSetupRouteImport.update({
  id: '/claude-setup',
  path: '/claude-setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChatgptSetupRoute = DocsChatgptSetupRouteImport.update({
  id: '/chatgpt-setup',
  path: '/chatgpt-setup',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/chatgpt-setup': typeof DocsChatgptSetupRoute
  '/docs/claude-setup': typeof DocsClaudeSetupRoute
  '/docs/collaborate': typeof DocsCollaborateRoute
  '/docs/data-flow': typeof DocsDataFlowRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/first-workspace': typeof DocsFirstWorkspaceRoute
  '/docs/hashing': typeof DocsHashingRoute
  '/docs/help': typeof DocsHelpRoute
  '/docs/importing-csv': typeof DocsImportingCsvRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/querying': typeof DocsQueryingRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/report-bug': typeof DocsReportBugRoute
  '/docs/sample-data': typeof DocsSampleDataRoute
  '/docs/share-chat': typeof DocsShareChatRoute
  '/docs/sharing': typeof DocsSharingRoute
  '/docs/sql-history': typeof DocsSqlHistoryRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/uninstall': typeof DocsUninstallRoute
  '/docs/workspaces': typeof DocsWorkspacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/chatgpt-setup': typeof DocsChatgptSetupRoute
  '/docs/claude-setup': typeof DocsClaudeSetupRoute
  '/docs/collaborate': typeof DocsCollaborateRoute
  '/docs/data-flow': typeof DocsDataFlowRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/first-workspace': typeof DocsFirstWorkspaceRoute
  '/docs/hashing': typeof DocsHashingRoute
  '/docs/help': typeof DocsHelpRoute
  '/docs/importing-csv': typeof DocsImportingCsvRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/querying': typeof DocsQueryingRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/report-bug': typeof DocsReportBugRoute
  '/docs/sample-data': typeof DocsSampleDataRoute
  '/docs/share-chat': typeof DocsShareChatRoute
  '/docs/sharing': typeof DocsSharingRoute
  '/docs/sql-history': typeof DocsSqlHistoryRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/uninstall': typeof DocsUninstallRoute
  '/docs/workspaces': typeof DocsWorkspacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/chatgpt-setup': typeof DocsChatgptSetupRoute
  '/docs/claude-setup': typeof DocsClaudeSetupRoute
  '/docs/collaborate': typeof DocsCollaborateRoute
  '/docs/data-flow': typeof DocsDataFlowRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/first-workspace': typeof DocsFirstWorkspaceRoute
  '/docs/hashing': typeof DocsHashingRoute
  '/docs/help': typeof DocsHelpRoute
  '/docs/importing-csv': typeof DocsImportingCsvRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/querying': typeof DocsQueryingRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/report-bug': typeof DocsReportBugRoute
  '/docs/sample-data': typeof DocsSampleDataRoute
  '/docs/share-chat': typeof DocsShareChatRoute
  '/docs/sharing': typeof DocsSharingRoute
  '/docs/sql-history': typeof DocsSqlHistoryRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/uninstall': typeof DocsUninstallRoute
  '/docs/workspaces': typeof DocsWorkspacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/chatgpt-setup'
    | '/docs/claude-setup'
    | '/docs/collaborate'
    | '/docs/data-flow'
    | '/docs/faq'
    | '/docs/first-workspace'
    | '/docs/hashing'
    | '/docs/help'
    | '/docs/importing-csv'
    | '/docs/installation'
    | '/docs/privacy'
    | '/docs/querying'
    | '/docs/quick-start'
    | '/docs/report-bug'
    | '/docs/sample-data'
    | '/docs/share-chat'
    | '/docs/sharing'
    | '/docs/sql-history'
    | '/docs/troubleshooting'
    | '/docs/uninstall'
    | '/docs/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/chatgpt-setup'
    | '/docs/claude-setup'
    | '/docs/collaborate'
    | '/docs/data-flow'
    | '/docs/faq'
    | '/docs/first-workspace'
    | '/docs/hashing'
    | '/docs/help'
    | '/docs/importing-csv'
    | '/docs/installation'
    | '/docs/privacy'
    | '/docs/querying'
    | '/docs/quick-start'
    | '/docs/report-bug'
    | '/docs/sample-data'
    | '/docs/share-chat'
    | '/docs/sharing'
    | '/docs/sql-history'
    | '/docs/troubleshooting'
    | '/docs/uninstall'
    | '/docs/workspaces'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/chatgpt-setup'
    | '/docs/claude-setup'
    | '/docs/collaborate'
    | '/docs/data-flow'
    | '/docs/faq'
    | '/docs/first-workspace'
    | '/docs/hashing'
    | '/docs/help'
    | '/docs/importing-csv'
    | '/docs/installation'
    | '/docs/privacy'
    | '/docs/querying'
    | '/docs/quick-start'
    | '/docs/report-bug'
    | '/docs/sample-data'
    | '/docs/share-chat'
    | '/docs/sharing'
    | '/docs/sql-history'
    | '/docs/troubleshooting'
    | '/docs/uninstall'
    | '/docs/workspaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/workspaces': {
      id: '/docs/workspaces'
      path: '/workspaces'
      fullPath: '/docs/workspaces'
      preLoaderRoute: typeof DocsWorkspacesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/uninstall': {
      id: '/docs/uninstall'
      path: '/uninstall'
      fullPath: '/docs/uninstall'
      preLoaderRoute: typeof DocsUninstallRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sql-history': {
      id: '/docs/sql-history'
      path: '/sql-history'
      fullPath: '/docs/sql-history'
      preLoaderRoute: typeof DocsSqlHistoryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sharing': {
      id: '/docs/sharing'
      path: '/sharing'
      fullPath: '/docs/sharing'
      preLoaderRoute: typeof DocsSharingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/share-chat': {
      id: '/docs/share-chat'
      path: '/share-chat'
      fullPath: '/docs/share-chat'
      preLoaderRoute: typeof DocsShareChatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sample-data': {
      id: '/docs/sample-data'
      path: '/sample-data'
      fullPath: '/docs/sample-data'
      preLoaderRoute: typeof DocsSampleDataRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/report-bug': {
      id: '/docs/report-bug'
      path: '/report-bug'
      fullPath: '/docs/report-bug'
      preLoaderRoute: typeof DocsReportBugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/querying': {
      id: '/docs/querying'
      path: '/querying'
      fullPath: '/docs/querying'
      preLoaderRoute: typeof DocsQueryingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/privacy': {
      id: '/docs/privacy'
      path: '/privacy'
      fullPath: '/docs/privacy'
      preLoaderRoute: typeof DocsPrivacyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/importing-csv': {
      id: '/docs/importing-csv'
      path: '/importing-csv'
      fullPath: '/docs/importing-csv'
      preLoaderRoute: typeof DocsImportingCsvRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/help': {
      id: '/docs/help'
      path: '/help'
      fullPath: '/docs/help'
      preLoaderRoute: typeof DocsHelpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/hashing': {
      id: '/docs/hashing'
      path: '/hashing'
      fullPath: '/docs/hashing'
      preLoaderRoute: typeof DocsHashingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/first-workspace': {
      id: '/docs/first-workspace'
      path: '/first-workspace'
      fullPath: '/docs/first-workspace'
      preLoaderRoute: typeof DocsFirstWorkspaceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/data-flow': {
      id: '/docs/data-flow'
      path: '/data-flow'
      fullPath: '/docs/data-flow'
      preLoaderRoute: typeof DocsDataFlowRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/collaborate': {
      id: '/docs/collaborate'
      path: '/collaborate'
      fullPath: '/docs/collaborate'
      preLoaderRoute: typeof DocsCollaborateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/claude-setup': {
      id: '/docs/claude-setup'
      path: '/claude-setup'
      fullPath: '/docs/claude-setup'
      preLoaderRoute: typeof DocsClaudeSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/chatgpt-setup': {
      id: '/docs/chatgpt-setup'
      path: '/chatgpt-setup'
      fullPath: '/docs/chatgpt-setup'
      preLoaderRoute: typeof DocsChatgptSetupRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsChatgptSetupRoute: typeof DocsChatgptSetupRoute
  DocsClaudeSetupRoute: typeof DocsClaudeSetupRoute
  DocsCollaborateRoute: typeof DocsCollaborateRoute
  DocsDataFlowRoute: typeof DocsDataFlowRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFirstWorkspaceRoute: typeof DocsFirstWorkspaceRoute
  DocsHashingRoute: typeof DocsHashingRoute
  DocsHelpRoute: typeof DocsHelpRoute
  DocsImportingCsvRoute: typeof DocsImportingCsvRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPrivacyRoute: typeof DocsPrivacyRoute
  DocsQueryingRoute: typeof DocsQueryingRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsReportBugRoute: typeof DocsReportBugRoute
  DocsSampleDataRoute: typeof DocsSampleDataRoute
  DocsShareChatRoute: typeof DocsShareChatRoute
  DocsSharingRoute: typeof DocsSharingRoute
  DocsSqlHistoryRoute: typeof DocsSqlHistoryRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsUninstallRoute: typeof DocsUninstallRoute
  DocsWorkspacesRoute: typeof DocsWorkspacesRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsChatgptSetupRoute: DocsChatgptSetupRoute,
  DocsClaudeSetupRoute: DocsClaudeSetupRoute,
  DocsCollaborateRoute: DocsCollaborateRoute,
  DocsDataFlowRoute: DocsDataFlowRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsFirstWorkspaceRoute: DocsFirstWorkspaceRoute,
  DocsHashingRoute: DocsHashingRoute,
  DocsHelpRoute: DocsHelpRoute,
  DocsImportingCsvRoute: DocsImportingCsvRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPrivacyRoute: DocsPrivacyRoute,
  DocsQueryingRoute: DocsQueryingRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsReportBugRoute: DocsReportBugRoute,
  DocsSampleDataRoute: DocsSampleDataRoute,
  DocsShareChatRoute: DocsShareChatRoute,
  DocsSharingRoute: DocsSharingRoute,
  DocsSqlHistoryRoute: DocsSqlHistoryRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsUninstallRoute: DocsUninstallRoute,
  DocsWorkspacesRoute: DocsWorkspacesRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
